module.exports = {
  TestAction: require('./TestAction.js'),
  TestActionFeedback: require('./TestActionFeedback.js'),
  TestActionGoal: require('./TestActionGoal.js'),
  TestActionResult: require('./TestActionResult.js'),
  TestFeedback: require('./TestFeedback.js'),
  TestGoal: require('./TestGoal.js'),
  TestRequestAction: require('./TestRequestAction.js'),
  TestRequestActionFeedback: require('./TestRequestActionFeedback.js'),
  TestRequestActionGoal: require('./TestRequestActionGoal.js'),
  TestRequestActionResult: require('./TestRequestActionResult.js'),
  TestRequestFeedback: require('./TestRequestFeedback.js'),
  TestRequestGoal: require('./TestRequestGoal.js'),
  TestRequestResult: require('./TestRequestResult.js'),
  TestResult: require('./TestResult.js'),
  TwoIntsAction: require('./TwoIntsAction.js'),
  TwoIntsActionFeedback: require('./TwoIntsActionFeedback.js'),
  TwoIntsActionGoal: require('./TwoIntsActionGoal.js'),
  TwoIntsActionResult: require('./TwoIntsActionResult.js'),
  TwoIntsFeedback: require('./TwoIntsFeedback.js'),
  TwoIntsGoal: require('./TwoIntsGoal.js'),
  TwoIntsResult: require('./TwoIntsResult.js'),
};
