//-----------------------------------------------------------
// Auto-generated from package actionlib.
// !! Do not edit !!
//-----------------------------------------------------------

"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength
const TestRequestActionGoal = require('./TestRequestActionGoal.js');
const TestRequestActionResult = require('./TestRequestActionResult.js');
const TestRequestActionFeedback = require('./TestRequestActionFeedback.js');

//-----------------------------------------------------------

class TestRequestAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      // check for this message's fields by key name - otherwise assign default values
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal;
      }
      else {
        this.action_goal = new TestRequestActionGoal();
      }

      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result;
      }
      else {
        this.action_result = new TestRequestActionResult();
      }

      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback;
      }
      else {
        this.action_feedback = new TestRequestActionFeedback();
      }

    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TestRequestAction
    // Serialize message field [action_goal]
    bufferOffset = TestRequestActionGoal.serialize(obj.action_goal, buffer, bufferOffset);

    // Serialize message field [action_result]
    bufferOffset = TestRequestActionResult.serialize(obj.action_result, buffer, bufferOffset);

    // Serialize message field [action_feedback]
    bufferOffset = TestRequestActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);

    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    // Deserializes a message object of type TestRequestAction
    let data = new TestRequestAction(null);
    let len;
    // Deserialize message field [action_goal]
    data.action_goal = TestRequestActionGoal.deserialize(buffer, bufferOffset);

    // Deserialize message field [action_result]
    data.action_result = TestRequestActionResult.deserialize(buffer, bufferOffset);

    // Deserialize message field [action_feedback]
    data.action_feedback = TestRequestActionFeedback.deserialize(buffer, bufferOffset);

    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += TestRequestActionGoal.getMessageSize(object.action_goal)
    length += TestRequestActionResult.getMessageSize(object.action_result)
    length += TestRequestActionFeedback.getMessageSize(object.action_feedback)
    return length;
  }

  static datatype() {
    // Returns string type for a actionlib/TestRequestAction object
    return 'actionlib/TestRequestAction';
  }

  static md5sum() {
    // Returns md5sum of message object
    return 'dc44b1f4045dbf0d1db54423b3b86b30'
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

TestRequestActionGoal action_goal
TestRequestActionResult action_result
TestRequestActionFeedback action_feedback

================================================================================
MSG: actionlib/TestRequestActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
TestRequestGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id

================================================================================
MSG: actionlib/TestRequestGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 TERMINATE_SUCCESS = 0
int32 TERMINATE_ABORTED = 1
int32 TERMINATE_REJECTED = 2
int32 TERMINATE_LOSE = 3
int32 TERMINATE_DROP = 4
int32 TERMINATE_EXCEPTION = 5
int32 terminate_status
bool ignore_cancel  # If true, ignores requests to cancel
string result_text
int32 the_result    # Desired value for the_result in the Result
bool is_simple_client
duration delay_accept  # Delays accepting the goal by this amount of time
duration delay_terminate  # Delays terminating for this amount of time
duration pause_status  # Pauses the status messages for this amount of time

================================================================================
MSG: actionlib/TestRequestActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestRequestResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text

================================================================================
MSG: actionlib/TestRequestResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 the_result
bool is_simple_server

================================================================================
MSG: actionlib/TestRequestActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestRequestFeedback feedback

================================================================================
MSG: actionlib/TestRequestFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
`;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TestRequestAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = TestRequestActionGoal.Resolve(msg.action_goal);
    }
    else {
      resolved.action_goal = new TestRequestActionGoal();
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = TestRequestActionResult.Resolve(msg.action_result);
    }
    else {
      resolved.action_result = new TestRequestActionResult();
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = TestRequestActionFeedback.Resolve(msg.action_feedback);
    }
    else {
      resolved.action_feedback = new TestRequestActionFeedback();
    }

    return resolved;
  }
}

module.exports = TestRequestAction
