//-----------------------------------------------------------
// Auto-generated from package actionlib.
// !! Do not edit !!
//-----------------------------------------------------------

"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength
const TestActionGoal = require('./TestActionGoal.js');
const TestActionResult = require('./TestActionResult.js');
const TestActionFeedback = require('./TestActionFeedback.js');

//-----------------------------------------------------------

class TestAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      // check for this message's fields by key name - otherwise assign default values
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal;
      }
      else {
        this.action_goal = new TestActionGoal();
      }

      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result;
      }
      else {
        this.action_result = new TestActionResult();
      }

      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback;
      }
      else {
        this.action_feedback = new TestActionFeedback();
      }

    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TestAction
    // Serialize message field [action_goal]
    bufferOffset = TestActionGoal.serialize(obj.action_goal, buffer, bufferOffset);

    // Serialize message field [action_result]
    bufferOffset = TestActionResult.serialize(obj.action_result, buffer, bufferOffset);

    // Serialize message field [action_feedback]
    bufferOffset = TestActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);

    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    // Deserializes a message object of type TestAction
    let data = new TestAction(null);
    let len;
    // Deserialize message field [action_goal]
    data.action_goal = TestActionGoal.deserialize(buffer, bufferOffset);

    // Deserialize message field [action_result]
    data.action_result = TestActionResult.deserialize(buffer, bufferOffset);

    // Deserialize message field [action_feedback]
    data.action_feedback = TestActionFeedback.deserialize(buffer, bufferOffset);

    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += TestActionGoal.getMessageSize(object.action_goal)
    length += TestActionResult.getMessageSize(object.action_result)
    length += TestActionFeedback.getMessageSize(object.action_feedback)
    return length;
  }

  static datatype() {
    // Returns string type for a actionlib/TestAction object
    return 'actionlib/TestAction';
  }

  static md5sum() {
    // Returns md5sum of message object
    return '991e87a72802262dfbe5d1b3cf6efc9a'
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

TestActionGoal action_goal
TestActionResult action_result
TestActionFeedback action_feedback

================================================================================
MSG: actionlib/TestActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
TestGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id

================================================================================
MSG: actionlib/TestGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 goal

================================================================================
MSG: actionlib/TestActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text

================================================================================
MSG: actionlib/TestResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 result

================================================================================
MSG: actionlib/TestActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestFeedback feedback

================================================================================
MSG: actionlib/TestFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 feedback
`;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TestAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = TestActionGoal.Resolve(msg.action_goal);
    }
    else {
      resolved.action_goal = new TestActionGoal();
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = TestActionResult.Resolve(msg.action_result);
    }
    else {
      resolved.action_result = new TestActionResult();
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = TestActionFeedback.Resolve(msg.action_feedback);
    }
    else {
      resolved.action_feedback = new TestActionFeedback();
    }

    return resolved;
  }
}

module.exports = TestAction
