// Generated by gencpp from file fsae_electric_vehicle/Num.msg
// DO NOT EDIT!


#ifndef FSAE_ELECTRIC_VEHICLE_MESSAGE_NUM_H
#define FSAE_ELECTRIC_VEHICLE_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fsae_electric_vehicle
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : Value(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : Value(0.0)  {
  (void)_alloc;
    }



   typedef double _Value_type;
  _Value_type Value;





  typedef boost::shared_ptr< ::fsae_electric_vehicle::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsae_electric_vehicle::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::fsae_electric_vehicle::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::fsae_electric_vehicle::Num > NumPtr;
typedef boost::shared_ptr< ::fsae_electric_vehicle::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsae_electric_vehicle::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsae_electric_vehicle::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fsae_electric_vehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fsae_electric_vehicle': ['/src/catkin_ws/src/fsae_electric_vehicle/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsae_electric_vehicle::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsae_electric_vehicle::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsae_electric_vehicle::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "443763acfe626348dfcaaf050a8f1502";
  }

  static const char* value(const ::fsae_electric_vehicle::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x443763acfe626348ULL;
  static const uint64_t static_value2 = 0xdfcaaf050a8f1502ULL;
};

template<class ContainerAllocator>
struct DataType< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsae_electric_vehicle/Num";
  }

  static const char* value(const ::fsae_electric_vehicle::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Value\n\
";
  }

  static const char* value(const ::fsae_electric_vehicle::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsae_electric_vehicle::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsae_electric_vehicle::Num_<ContainerAllocator>& v)
  {
    s << indent << "Value: ";
    Printer<double>::stream(s, indent + "  ", v.Value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSAE_ELECTRIC_VEHICLE_MESSAGE_NUM_H
