// Generated by gencpp from file fsae_electric_vehicle/temp_and_pressure.msg
// DO NOT EDIT!


#ifndef FSAE_ELECTRIC_VEHICLE_MESSAGE_TEMP_AND_PRESSURE_H
#define FSAE_ELECTRIC_VEHICLE_MESSAGE_TEMP_AND_PRESSURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fsae_electric_vehicle
{
template <class ContainerAllocator>
struct temp_and_pressure_
{
  typedef temp_and_pressure_<ContainerAllocator> Type;

  temp_and_pressure_()
    : temp(0.0)
    , pressure(0.0)
    , time()  {
    }
  temp_and_pressure_(const ContainerAllocator& _alloc)
    : temp(0.0)
    , pressure(0.0)
    , time(_alloc)  {
  (void)_alloc;
    }



   typedef float _temp_type;
  _temp_type temp;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> const> ConstPtr;

}; // struct temp_and_pressure_

typedef ::fsae_electric_vehicle::temp_and_pressure_<std::allocator<void> > temp_and_pressure;

typedef boost::shared_ptr< ::fsae_electric_vehicle::temp_and_pressure > temp_and_pressurePtr;
typedef boost::shared_ptr< ::fsae_electric_vehicle::temp_and_pressure const> temp_and_pressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fsae_electric_vehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fsae_electric_vehicle': ['/home/nvidia/Github/formulaEmbedded/catkin_ws/src/fsae_electric_vehicle/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26c525dcd35afdc9fbc0cf3502593e9f";
  }

  static const char* value(const ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26c525dcd35afdc9ULL;
  static const uint64_t static_value2 = 0xfbc0cf3502593e9fULL;
};

template<class ContainerAllocator>
struct DataType< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsae_electric_vehicle/temp_and_pressure";
  }

  static const char* value(const ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temp\n\
float32 pressure\n\
string time\n\
";
  }

  static const char* value(const ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
      stream.next(m.pressure);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct temp_and_pressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsae_electric_vehicle::temp_and_pressure_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSAE_ELECTRIC_VEHICLE_MESSAGE_TEMP_AND_PRESSURE_H
