(cl:defpackage fsae_electric_vehicle-msg
  (:use )
  (:export
   "<ACCELEROMETER>"
   "ACCELEROMETER"
   "<COMPASS>"
   "COMPASS"
   "<GYROSCOPE>"
   "GYROSCOPE"
   "<IMU_DATA>"
   "IMU_DATA"
   "<PEDALS>"
   "PEDALS"
   "<STEERING_INPUT>"
   "STEERING_INPUT"
   "<STEERING_WHEEL>"
   "STEERING_WHEEL"
   "<SUSPENSION>"
   "SUSPENSION"
   "<SUSPENSION_OFFSET>"
   "SUSPENSION_OFFSET"
   "<TEMP_AND_PRESSURE>"
   "TEMP_AND_PRESSURE"
   "<TIRE_PRESSURE>"
   "TIRE_PRESSURE"
   "<WHEEL_VELOCITY>"
   "WHEEL_VELOCITY"
  ))

