# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsae_electric_vehicle/suspension_offset.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class suspension_offset(genpy.Message):
  _md5sum = "efe3c26acf397027388f0a2994b3fca9"
  _type = "fsae_electric_vehicle/suspension_offset"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 front_left_value 
float32 front_right_value 
float32 back_left_value 
float32 back_right_value 
string time_collected
"""
  __slots__ = ['front_left_value','front_right_value','back_left_value','back_right_value','time_collected']
  _slot_types = ['float32','float32','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front_left_value,front_right_value,back_left_value,back_right_value,time_collected

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(suspension_offset, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front_left_value is None:
        self.front_left_value = 0.
      if self.front_right_value is None:
        self.front_right_value = 0.
      if self.back_left_value is None:
        self.back_left_value = 0.
      if self.back_right_value is None:
        self.back_right_value = 0.
      if self.time_collected is None:
        self.time_collected = ''
    else:
      self.front_left_value = 0.
      self.front_right_value = 0.
      self.back_left_value = 0.
      self.back_right_value = 0.
      self.time_collected = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.front_left_value, _x.front_right_value, _x.back_left_value, _x.back_right_value))
      _x = self.time_collected
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.front_left_value, _x.front_right_value, _x.back_left_value, _x.back_right_value,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.time_collected = str[start:end].decode('utf-8')
      else:
        self.time_collected = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.front_left_value, _x.front_right_value, _x.back_left_value, _x.back_right_value))
      _x = self.time_collected
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.front_left_value, _x.front_right_value, _x.back_left_value, _x.back_right_value,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.time_collected = str[start:end].decode('utf-8')
      else:
        self.time_collected = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
