# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsae_electric_vehicle/wheel_velocity.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class wheel_velocity(genpy.Message):
  _md5sum = "8a6ea563b0ec5361d7adcaeba167aaab"
  _type = "fsae_electric_vehicle/wheel_velocity"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 front_left_value
string front_left_time
float32 front_right_value
string front_right_time
float32 back_left_value
string back_left_time
float32 back_right_value
string back_right_time
"""
  __slots__ = ['front_left_value','front_left_time','front_right_value','front_right_time','back_left_value','back_left_time','back_right_value','back_right_time']
  _slot_types = ['float32','string','float32','string','float32','string','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front_left_value,front_left_time,front_right_value,front_right_time,back_left_value,back_left_time,back_right_value,back_right_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(wheel_velocity, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front_left_value is None:
        self.front_left_value = 0.
      if self.front_left_time is None:
        self.front_left_time = ''
      if self.front_right_value is None:
        self.front_right_value = 0.
      if self.front_right_time is None:
        self.front_right_time = ''
      if self.back_left_value is None:
        self.back_left_value = 0.
      if self.back_left_time is None:
        self.back_left_time = ''
      if self.back_right_value is None:
        self.back_right_value = 0.
      if self.back_right_time is None:
        self.back_right_time = ''
    else:
      self.front_left_value = 0.
      self.front_left_time = ''
      self.front_right_value = 0.
      self.front_right_time = ''
      self.back_left_value = 0.
      self.back_left_time = ''
      self.back_right_value = 0.
      self.back_right_time = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_f().pack(self.front_left_value))
      _x = self.front_left_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.front_right_value))
      _x = self.front_right_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.back_left_value))
      _x = self.back_left_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.back_right_value))
      _x = self.back_right_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.front_left_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front_left_time = str[start:end].decode('utf-8')
      else:
        self.front_left_time = str[start:end]
      start = end
      end += 4
      (self.front_right_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front_right_time = str[start:end].decode('utf-8')
      else:
        self.front_right_time = str[start:end]
      start = end
      end += 4
      (self.back_left_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.back_left_time = str[start:end].decode('utf-8')
      else:
        self.back_left_time = str[start:end]
      start = end
      end += 4
      (self.back_right_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.back_right_time = str[start:end].decode('utf-8')
      else:
        self.back_right_time = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_f().pack(self.front_left_value))
      _x = self.front_left_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.front_right_value))
      _x = self.front_right_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.back_left_value))
      _x = self.back_left_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_f().pack(self.back_right_value))
      _x = self.back_right_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.front_left_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front_left_time = str[start:end].decode('utf-8')
      else:
        self.front_left_time = str[start:end]
      start = end
      end += 4
      (self.front_right_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.front_right_time = str[start:end].decode('utf-8')
      else:
        self.front_right_time = str[start:end]
      start = end
      end += 4
      (self.back_left_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.back_left_time = str[start:end].decode('utf-8')
      else:
        self.back_left_time = str[start:end]
      start = end
      end += 4
      (self.back_right_value,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.back_right_time = str[start:end].decode('utf-8')
      else:
        self.back_right_time = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
